In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
arr_1 = np.array([1,2,3,4,5], ndmin= 2)
arr_1

array([[1, 2, 3, 4, 5]])

In [3]:
print(f"Type: {type(arr_1)}")
print(f"Shape: {arr_1.shape}")
print(f"Dimension: {arr_1.ndim}")

Type: <class 'numpy.ndarray'>
Shape: (1, 5)
Dimension: 2


In [4]:
arr_2 = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
print(f"Type: {type(arr_2)}")
print(f"Shape: {arr_2.shape}")
print(f"Dimension: {arr_2.ndim}")

Type: <class 'numpy.ndarray'>
Shape: (2, 4)
Dimension: 2


# Addition & Multiplication

In [7]:
matrice_1 = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [8,9,6,5]])

matrice_2 = np.array([[-1,4,3,5],
                     [1,4,7,9],
                     [-6,5,11,-4]])

print(f"Matrice_1: \n{matrice_1}", "\n")
print(f"Shape of Matrice_1: {matrice_1.shape}")
print(f"\nMatrice_2: \n{matrice_1.shape}","\n")
print(f"Shape of Matrice 2: {matrice_2.shape}")
print(f"Matrice_2: \n{matrice_2}", "\n")

Matrice_1: 
[[1 2 3 4]
 [5 6 7 8]
 [8 9 6 5]] 

Shape of Matrice_1: (3, 4)

Matrice_2: 
(3, 4) 

Shape of Matrice 2: (3, 4)
Matrice_2: 
[[-1  4  3  5]
 [ 1  4  7  9]
 [-6  5 11 -4]] 



In [8]:
matrice_1 + matrice_2

array([[ 0,  6,  6,  9],
       [ 6, 10, 14, 17],
       [ 2, 14, 17,  1]])

In [10]:
matrice_1 - matrice_2

array([[ 2, -2,  0, -1],
       [ 4,  2,  0, -1],
       [14,  4, -5,  9]])

# Multiplication

In [13]:
#Multiplication

In [14]:
matrice_3 = matrice_1 * matrice_2

In [15]:
matrice_3

array([[ -1,   8,   9,  20],
       [  5,  24,  49,  72],
       [-48,  45,  66, -20]])

In [16]:
M = np.array([[6, 1, 3],
             [-1, 1, 1],
            [1, 4, 5]])

v = np.array([1, 2, 3])

print(f"Shape of matrix M = {M.shape}", "\n", f"Shape of vector v = {v.shape}")

Shape of matrix M = (3, 3) 
 Shape of vector v = (3,)


In [17]:
6*1 + 1*2 + 3*3

17

In [18]:
M.dot(v)

array([17,  4, 24])

In [19]:
np.dot(M,v)

array([17,  4, 24])

In [21]:
C = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 8, 6, 5]])

db = np.array([[3, 4, 5, 6],
              [8, 5, 6, 3],
              [7, 5, 3, 4],
              [2, 6, 7, 4]])

D = np.array([[-1, 4, 3, 5],
             [1, 4, 7, 9],
             [-6, 5, 4, -8]]).reshape(4,3)
print(f"Shape of matrix C = {C.shape}", "\n", f"Shape of matrix D = {D.shape}")
print(D)

Shape of matrix C = (3, 4) 
 Shape of matrix D = (4, 3)
[[-1  4  3]
 [ 5  1  4]
 [ 7  9 -6]
 [ 5  4 -8]]


In [22]:
C.dot(D)

array([[ 50,  49, -39],
       [114, 121, -67],
       [ 98, 118, -17]])

In [23]:
np.dot(C,D)

array([[ 50,  49, -39],
       [114, 121, -67],
       [ 98, 118, -17]])

# New Program

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing()

In [3]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [5]:
def round_expr(expr, num_digits):
    return expr.xreplace({n: round(n, num_digits) for n in expr.atoms(sy.Number)})

In [6]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
B

array([[5, 6],
       [7, 8]])

In [9]:
A*B

array([[ 5, 12],
       [21, 32]])

In [10]:
A@B

array([[19, 22],
       [43, 50]])

In [11]:
np.sum(A[0,:]*B[:,0])
np.sum(A[1,:]*B[:,0])
np.sum(A[0,:]*B[:,1])
np.sum(A[1,:]*B[:,1])

19

43

22

50

In [15]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real= True)

In [16]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z

In [17]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [18]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

In [19]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [20]:
AB = A*B; AB
AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

In [21]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B
B-A

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

⎡2   -1⎤
⎢      ⎥
⎣-5  -7⎦

In [22]:
A+B

⎡8  7⎤
⎢    ⎥
⎣9  9⎦

In [23]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
A-B

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a - e  b - f⎤
⎢            ⎥
⎣c - g  d - h⎦

In [24]:
A+B

⎡a + e  b + f⎤
⎢            ⎥
⎣c + g  d + h⎦

In [25]:
M = A*B - B*A
M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

In [26]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d-a, -c], [0, c, -b, 0]]);
A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

In [27]:
M = A*B - B*A
M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

In [28]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d-a, -c], [0, c, -b, 0]]);
A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

In [29]:
A_aug.rref()

⎛⎡      -(a - d)     ⎤        ⎞
⎜⎢1  0  ─────────  -1⎥        ⎟
⎜⎢          c        ⎥        ⎟
⎜⎢                   ⎥        ⎟
⎜⎢         -b        ⎥        ⎟
⎜⎢0  1     ───     0 ⎥, (0, 1)⎟
⎜⎢          c        ⎥        ⎟
⎜⎢                   ⎥        ⎟
⎜⎢0  0      0      0 ⎥        ⎟
⎜⎢                   ⎥        ⎟
⎝⎣0  0      0      0 ⎦        ⎠

In [30]:
C = sy.Matrix([[1.1, 0.6], [1, 1]]);
C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

In [31]:
A = sy.Matrix([[10, 12], [20, 18]])
A*C

⎡23.0  18.0⎤
⎢          ⎥
⎣40.0  30.0⎦

In [32]:
C*A

⎡23.0  24.0⎤
⎢          ⎥
⎣ 30    30 ⎦

In [33]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]);
A

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

In [34]:
A.T

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

In [35]:
A.transpose()

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

In [38]:
A

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

In [39]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B

AB_tr = AB.transpose();
AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [40]:
A

⎡a  b⎤
⎢    ⎥
⎢c  d⎥
⎢    ⎥
⎣e  f⎦

In [41]:
B

⎡g  h  i⎤
⎢       ⎥
⎣j  k  l⎦

In [42]:
B.T

⎡g  j⎤
⎢    ⎥
⎢h  k⎥
⎢    ⎥
⎣i  l⎦

In [43]:
A.T

⎡a  c  e⎤
⎢       ⎥
⎣b  d  f⎦

In [44]:
A_tr_B_tr = B.transpose();
AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

In [45]:
AB_tr - A_tr_B_tr

ShapeError: Matrix size mismatch: (3, 3) + (3, 2)

In [46]:
I = np.eye(5);
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
A = np.around(np.random.rand(5, 5)*100);
A

array([[32., 35., 55., 33., 84.],
       [90., 35., 81., 28., 76.],
       [61., 91., 33.,  2., 65.],
       [47., 96., 22., 74., 80.],
       [29., 73., 64., 91., 34.]])

In [48]:
A@I

array([[32., 35., 55., 33., 84.],
       [90., 35., 81., 28., 76.],
       [61., 91., 33.,  2., 65.],
       [47., 96., 22., 74., 80.],
       [29., 73., 64., 91., 34.]])

In [49]:
I@A

array([[32., 35., 55., 33., 84.],
       [90., 35., 81., 28., 76.],
       [61., 91., 33.,  2., 65.],
       [47., 96., 22., 74., 80.],
       [29., 73., 64., 91., 34.]])

In [50]:
A = sy.randMatrix(3, percent = 80);
A

⎡82  92  34⎤
⎢          ⎥
⎢34  73  0 ⎥
⎢          ⎥
⎣54  13  59⎦

In [51]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);
E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

In [52]:
E*A

⎡34  73  0 ⎤
⎢          ⎥
⎢82  92  34⎥
⎢          ⎥
⎣54  13  59⎦