In [6]:
import pandas as pd
import numpy as np
import sympy as sy
import scipy as sp
import scipy.linalg
from mpl_toolkits.mplot3d import Axes3D
sy.init_printing()

In [7]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [9]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [10]:
def round_expr(expr, num_digits):
    return expr.xreplace({n: round(n, num_digits) for n in expr.atoms(sy.Number)})

In [11]:
a, b, c, d, e, f, g, h, i = sy.symbols('a, b, c, d, e, f, g, h, i', real = True)
a, b, c, d, e, f, g, h, i

In [12]:
A = sy.Matrix([[a, b], [c, d]])
A.det()

In [13]:
B = sy.Matrix([[a, b, c], [d, e, f], [g, h, i]])
B.det()

In [14]:
B

⎡a  b  c⎤
⎢       ⎥
⎢d  e  f⎥
⎢       ⎥
⎣g  h  i⎦

In [15]:
B.det()

In [16]:
A

⎡a  b⎤
⎢    ⎥
⎣c  d⎦

In [17]:
A.det()

In [18]:
A = sy.Matrix([[49, 0, 61], [73, 22, 96], [2, 0, 32]]);
A

⎡49  0   61⎤
⎢          ⎥
⎢73  22  96⎥
⎢          ⎥
⎣2   0   32⎦

In [20]:
A.det()

In [21]:
def cof_exp(matrix, c):
    detA = 0
    for i in range(matrix.shape[1]):
        detA += matrix[i, c]* (-1)**(i+c)*sy.matrices.MatrixDeterminant.minor(matrix, i, c)
    return detA

In [22]:
detA

NameError: name 'detA' is not defined

In [23]:
cof_exp(A,1)

In [24]:
B = sy.randMatrix(r = 7, min= 10, max= 50, percent=70);
B

⎡0   22  34  43  39  18  10⎤
⎢                          ⎥
⎢0   30  37  13  41  0   40⎥
⎢                          ⎥
⎢43  0   35  28  0   23  45⎥
⎢                          ⎥
⎢46  0   0   0   42  13  39⎥
⎢                          ⎥
⎢29  0   13  0   10  18  45⎥
⎢                          ⎥
⎢0   16  47  41  44  0   44⎥
⎢                          ⎥
⎣43  0   41  47  45  0   19⎦

In [25]:
B.det()

In [26]:
cof_exp(B, 1)

In [27]:
sy.matrices.MatrixDeterminant.minor_submatrix(B, 2, 3)

⎡0   22  34  39  18  10⎤
⎢                      ⎥
⎢0   30  37  41  0   40⎥
⎢                      ⎥
⎢46  0   0   42  13  39⎥
⎢                      ⎥
⎢29  0   13  10  18  45⎥
⎢                      ⎥
⎢0   16  47  44  0   44⎥
⎢                      ⎥
⎣43  0   41  45  0   19⎦

In [28]:
sy.matrices.MatrixDeterminant.cofactor_matrix(A)

⎡ 704   -2144  -44 ⎤
⎢                  ⎥
⎢  0    1446    0  ⎥
⎢                  ⎥
⎣-1342  -251   1078⎦

In [29]:
A

⎡49  0   61⎤
⎢          ⎥
⎢73  22  96⎥
⎢          ⎥
⎣2   0   32⎦

In [30]:
sy.matrices.MatrixDeterminant.cofactor_matrix(B)

⎡236771686    160497239   -257495862    150053410   -312955406   -996188836   
⎢                                                                             
⎢-395728094  -1008918388  -386144946    485171686    147201142    384517268   
⎢                                                                             
⎢-758221710  -2122282422  1836600312   -1735868112  1183367772   1127565078   
⎢                                                                             
⎢-512112786  -1545934194  2170378524   -1480906428   376422156    930170604   
⎢                                                                             
⎢1101926400  3667816107   -3656766804  3137543820   -1470986082  -2505826230  
⎢                                                                             
⎢416429108    107909740   1078078584   -1116020350   154311542    648789772   
⎢                                                                             
⎣-18725592   1302429069   -1692209028  1204075668   

In [31]:
A = np.round(np.random.rand(5,5)*100)
A_triu = np.triu(A);
A_triu

array([[81., 23., 35., 42., 36.],
       [ 0.,  0., 75., 83.,  9.],
       [ 0.,  0., 89., 92., 82.],
       [ 0.,  0.,  0., 92., 81.],
       [ 0.,  0.,  0.,  0., 95.]])

In [32]:
A

array([[81., 23., 35., 42., 36.],
       [79.,  0., 75., 83.,  9.],
       [52., 78., 89., 92., 82.],
       [36., 67., 75., 92., 81.],
       [36., 97., 70., 16., 95.]])

In [33]:
np.linalg.det(A_triu)

In [35]:
B.det()

In [36]:
A_diag = np.diag(A_triu)
np.prod(A_diag)

In [37]:
A = np.array([[2, -1, 3], [3, 3, -1], [-1, -1, 1]])
print(A)
b = np.array([-3, 10, -4])
print(b)

[[ 2 -1  3]
 [ 3  3 -1]
 [-1 -1  1]]
[-3 10 -4]


In [38]:
A_1b = np.copy(A)
A_1b[:, 0]=b

A_2b = np.copy(A)
A_2b[:, 1]= b

A_3b = np.copy(A)
A_3b[:, 2]=b

In [39]:
b

array([-3, 10, -4])

In [40]:
A_2b

array([[ 2, -3,  3],
       [ 3, 10, -1],
       [-1, -4,  1]])

In [41]:
A_1b

array([[-3, -1,  3],
       [10,  3, -1],
       [-4, -1,  1]])

In [42]:
x1 = np.linalg.det(A_1b)/np.linalg.det(A)
print(x1)
x2 = np.linalg.det(A_2b)/np.linalg.det(A)
print(x2)
x3 = np.linalg.det(A_3b)/np.linalg.det(A)
print(x2)

(x1, x2, x3)

1.0000000000000004
1.9999999999999982
1.9999999999999982


In [43]:
np.linalg.solve(A, b)

array([ 1.,  2., -1.])

In [44]:
np.linalg.inv(A)@b

array([ 1.,  2., -1.])

In [45]:
A = sy.randMatrix(5, min = -5, max= 5, percent= 80);
A

⎡0   -2  0   0   -4⎤
⎢                  ⎥
⎢4   3   3   -4  -5⎥
⎢                  ⎥
⎢0   4   3   -5  -2⎥
⎢                  ⎥
⎢4   -3  1   1   5 ⎥
⎢                  ⎥
⎣-1  -5  -5  5   0 ⎦

In [46]:
A_adjugate = sy.matrices.MatrixDeterminant.adjugate(A);
A_adjugate

⎡-135  180  -30    60   102 ⎤
⎢                           ⎥
⎢-239  128  -212  -148  -80 ⎥
⎢                           ⎥
⎢282   -90  -414  -30   -480⎥
⎢                           ⎥
⎢ 16   74   -632  -166  -368⎥
⎢                           ⎥
⎣-95   -64  106    74    40 ⎦

In [47]:
(-1)**(1+3) * sy.matrices.MatrixDeterminant.minor(A, 0, 2)
(-1)**(2+4) * sy.matrices.MatrixDeterminant.minor(A, 3, 1)
(-1)**(5+4) * sy.matrices.MatrixDeterminant.minor(A, 3, 4)

In [48]:
(-1)**(3+4) * sy.matrices.MatrixDeterminant.minor(A, 0, 2)

In [51]:
A_det = A.det()
A_inv = (1/A_det)*A_adjugate;
round_expr(sy.N(A_inv), 4)

⎡-0.1573  0.2098   -0.035   0.0699   0.1189 ⎤
⎢                                           ⎥
⎢-0.2786  0.1492   -0.2471  -0.1725  -0.0932⎥
⎢                                           ⎥
⎢0.3287   -0.1049  -0.4825  -0.035   -0.5594⎥
⎢                                           ⎥
⎢0.0186   0.0862   -0.7366  -0.1935  -0.4289⎥
⎢                                           ⎥
⎣-0.1107  -0.0746  0.1235   0.0862   0.0466 ⎦

In [52]:
A_inv-A.inv()

⎡0  0  0  0  0⎤
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎢0  0  0  0  0⎥
⎢             ⎥
⎣0  0  0  0  0⎦